name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      # Set up Google Cloud SDK and authenticate using the service account key
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.0
        with:
          project_id: docker-deploy-454713 # Your GCP project ID
          service_account_key: ${{ secrets.GCP_CREDENTIALS }} # GitHub Secret for service account key

      - name: Build Docker image
        run: |
          docker build -t asia-southeast2-docker.pkg.dev/docker-deploy-454713/docker-deploy-artifact/docker-deploy:v1 .

      - name: Push Docker image to Google Artifact Registry
        run: |
          docker push asia-southeast2-docker.pkg.dev/docker-deploy-454713/docker-deploy-artifact/docker-deploy:v1

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy docker-deploy \
            --image=asia-southeast2-docker.pkg.dev/docker-deploy-454713/docker-deploy-artifact/docker-deploy:v1 \
            --region=asia-southeast2 \
            --platform=managed \
            --allow-unauthenticated \
            --port=3000 \
            --set-env-vars NEXT_PUBLIC_CLIENT_VERSION=${{ secrets.NEXT_PUBLIC_CLIENT_VERSION }},SERVER_VERSION=${{ secrets.SERVER_VERSION }}
